name: Rust Setup
inputs:
  sha:
    required: true
  components:
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
