name: Rust Test
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  workflow_dispatch:

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/rust-setup
        with:
          components: rustfmt
      - run: cargo fmt --all --check

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/rust-setup
        with:
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings

  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/rust-setup
      - run: cargo test --verbose
